insert into public.projects (
    id, title_en, title_pt, short_description_en, short_description_pt,
    full_description_en, full_description_pt, preview, images,
    type, category, technologies, features, status, github_url, live_url
) overriding system value values (
    2, 'Lottus', 'Lottus', 'Academic library management platform built with Clean Architecture, Redis caching, and asynchronous processing.', 'Plataforma de gerenciamento de bibliotecas acadêmicas desenvolvida com Clean Architecture, cache Redis e processamento assíncrono.',
    'Lottus is a full-stack academic library management platform developed with a scalable backend architecture focused on performance, maintainability, and separation of concerns. The backend follows Clean Architecture principles and integrates Redis caching, RabbitMQ asynchronous processing, JWT authentication, and Dockerized infrastructure to support modern enterprise-grade development practices.', 'Lottus é uma plataforma full stack de gerenciamento de bibliotecas acadêmicas desenvolvida com uma arquitetura backend escalável, focada em desempenho, manutenibilidade e separação de responsabilidades. O backend segue os princípios da Clean Architecture e integra cache Redis, processamento assíncrono com RabbitMQ, autenticação JWT e infraestrutura conteinerizada com Docker, seguindo padrões adotados em ambientes de produção corporativos.', '/projects/lottus/lottus-preview.png', '{}',
    'Study Project', 'System', array['Java 21', 'Spring Boot', 'Spring Security', 'JWT', 'MySQL', 'Redis', 'RabbitMQ', 'Docker', 'Spring Data JPA', 'React', 'TailwindCSS']::text[], '[{"en":"Clean Architecture","pt":"Clean Architecture"},{"en":"Redis cache layer","pt":"Camada de cache com Redis"},{"en":"JWT authentication","pt":"Autenticação JWT"},{"en":"Asynchronous file processing","pt":"Processamento assíncrono de arquivos"},{"en":"RabbitMQ message broker integration","pt":"Integração com RabbitMQ"},{"en":"Dockerized infrastructure","pt":"Infraestrutura com Docker"},{"en":"Swagger API documentation","pt":"Documentação da API com Swagger"},{"en":"REST API architecture","pt":"Arquitetura REST API"},{"en":"Library loan management","pt":"Gerenciamento de empréstimos"},{"en":"Digital catalog system","pt":"Catálogo digital"},{"en":"Student and class management","pt":"Gerenciamento de alunos e turmas"}]'::jsonb, 'Completed', 'https://github.com/Lottus-Solutions', null
) on conflict (id) do nothing;

insert into public.projects (
    id, title_en, title_pt, short_description_en, short_description_pt,
    full_description_en, full_description_pt, preview, images,
    type, category, technologies, features, status, github_url, live_url
) overriding system value values (
    3, 'Lottus Mobile', 'Lottus Mobile', 'Mobile reading management platform designed for parents and students.', 'Plataforma mobile de acompanhamento de leitura desenvolvida para pais e alunos.',
    'Lottus Mobile is a full-stack platform designed to help parents track and manage their children''s school reading activities. The project includes a secure Spring Boot backend API and a React Native mobile application, focusing on authentication security, modular architecture, and scalable mobile-first experiences.', 'Lottus Mobile é uma plataforma full stack desenvolvida para auxiliar pais no acompanhamento das atividades de leitura escolar de seus filhos. O projeto combina uma API segura desenvolvida com Spring Boot e um aplicativo mobile construído com React Native, com foco em segurança de autenticação, arquitetura modular e uma experiência mobile-first bem estruturada.', '/projects/lottus/lottus-preview.png', '{}',
    'Study Project', 'Mobile App', array['Java 21', 'Spring Boot', 'Spring Security', 'JWT', 'OAuth2', 'Google OIDC', 'MySQL', 'Flyway', 'Swagger', 'Docker', 'React Native', 'TailwindCSS']::text[], '[{"en":"Mobile application for parents","pt":"Aplicativo mobile para pais"},{"en":"JWT authentication","pt":"Autenticação JWT"},{"en":"Google OAuth2 login","pt":"Login com Google OAuth2"},{"en":"Refresh token rotation","pt":"Refresh Token"},{"en":"Loan management","pt":"Gerenciamento de empréstimos"},{"en":"Student enrollment validation","pt":"Validação de matrícula"},{"en":"Swagger API documentation","pt":"Documentação da API com Swagger"},{"en":"Flyway database migrations","pt":"Migrações de banco com Flyway"},{"en":"Modular architecture by feature","pt":"Arquitetura modular por funcionalidade"},{"en":"Secure token storage","pt":"Armazenamento seguro de tokens"},{"en":"Dockerized database setup","pt":"Banco de dados com Docker"},{"en":"Mobile-first user experience","pt":"Experiência mobile-first"}]'::jsonb, 'In Progress', 'https://github.com/Lottus-Solutions', null
) on conflict (id) do nothing;

insert into public.projects (
    id, title_en, title_pt, short_description_en, short_description_pt,
    full_description_en, full_description_pt, preview, images,
    type, category, technologies, features, status, github_url, live_url
) overriding system value values (
    5, 'Portfolio', 'Portfolio', 'Personal developer portfolio showcasing projects and skills, with a custom CMS — a full-stack Next.js application with a TypeScript backend and PostgreSQL database.', 'Portfólio profissional desenvolvido para apresentar projetos e habilidades, com um CMS customizado — uma aplicação full stack em Next.js, com backend em TypeScript e banco de dados PostgreSQL.',
    'This portfolio was designed to showcase my projects, technical skills, and approach to software development through a modern full-stack application built entirely with Next.js and TypeScript. The frontend focuses on responsive design, reusable components, and user experience. The backend runs on Next.js API routes and Server Actions, backed by a PostgreSQL database (Neon), providing a custom CMS for managing portfolio content, JWT-based authentication for the admin panel, and email delivery for the contact form via Resend. The project emphasizes maintainability and real-world full-stack engineering practices within the Next.js ecosystem.', 'Este portfólio foi desenvolvido para apresentar meus projetos e habilidades técnicas por meio de uma aplicação full stack moderna, construída inteiramente com Next.js e TypeScript. O frontend prioriza responsividade, componentes reutilizáveis e experiência do usuário. O backend roda sobre API routes e Server Actions do Next.js, com banco de dados PostgreSQL (Neon), oferecendo um CMS customizado para gerenciamento de conteúdo, autenticação JWT para o painel administrativo e envio de e-mails do formulário de contato via Resend. O projeto tem como foco manutenibilidade e boas práticas de engenharia full stack dentro do ecossistema Next.js.', '/projects/portfolio/portfolio-preview.png', '{}',
    'Real Project', 'Portfolio', array['Next.js', 'React', 'TypeScript', 'TailwindCSS', 'PostgreSQL', 'Neon', 'JWT Authentication', 'Resend']::text[], '[{"en":"Responsive design","pt":"Design responsivo"},{"en":"Reusable UI components","pt":"Componentes reutilizáveis"},{"en":"Projects showcase","pt":"Seção de projetos"},{"en":"About section","pt":"Seção sobre mim"},{"en":"Contact section","pt":"Seção de contato"},{"en":"Next.js API routes and Server Actions","pt":"API routes e Server Actions do Next.js"},{"en":"JWT authentication and authorization","pt":"Autenticação e autorização JWT"},{"en":"Protected admin routes","pt":"Rotas administrativas protegidas"},{"en":"Contact email service","pt":"Serviço de envio de e-mails"},{"en":"Portfolio CMS management","pt":"Gerenciamento via CMS"},{"en":"Dynamic content management","pt":"Gerenciamento dinâmico de conteúdo"},{"en":"Environment-based configuration","pt":"Configuração por ambiente"},{"en":"PostgreSQL database via Neon","pt":"Banco de dados PostgreSQL com Neon"},{"en":"Internationalization (PT/EN) with next-intl","pt":"Internacionalização (PT/EN) com next-intl"},{"en":"Full-stack TypeScript architecture","pt":"Arquitetura full stack em TypeScript"}]'::jsonb, 'In Progress', 'https://github.com/nathannolacio/portfolio-frontend', null
) on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.projects', 'id'), (select max(id) from public.projects));
